version: '3'

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
